-- ============================================================
-- EDM 테스트 DB 스키마 생성 스크립트
-- Supabase SQL Editor에서 순서대로 실행하세요.
-- ============================================================

-- ── 0. 확장 활성화 ────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── 1. 의존성 없는 테이블 ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.companies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  email_domain character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.esg_category (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.master_sites (
  site_id text NOT NULL PRIMARY KEY,
  site_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.raw_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type character varying,
  site_id character varying,
  uploaded_by text,
  created_at timestamp with time zone DEFAULT now(),
  reporting_date date,
  metric_col text,
  raw_value text,
  source_file text,
  unit character varying
);

CREATE TABLE IF NOT EXISTS public.raw_ocr_data (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name text,
  raw_content jsonb,
  ocr_provider text,
  processing_status text,
  extracted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- ── 2. user_profiles (auth.users 참조) ────────────────────────
-- Supabase는 auth.users가 기본 제공됩니다.

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id),
  username character varying NOT NULL UNIQUE,
  display_name character varying,
  company_id bigint REFERENCES public.companies(id),
  work_email character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- ── 3. issues / indicators / data / data_points 계층 ──────────

CREATE TABLE IF NOT EXISTS public.issues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  esg_category_id integer REFERENCES public.esg_category(id),
  previous_years integer[] DEFAULT '{}'::integer[]
);

CREATE TABLE IF NOT EXISTS public.indicators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  issue_id bigint REFERENCES public.issues(id),
  frameworks jsonb,
  created_at timestamp with time zone DEFAULT now(),
  indicator_code character varying,
  standard_version character varying,
  effective_date date,
  disclosure_title text,
  requirement_text text
);

CREATE TABLE IF NOT EXISTS public.data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  indicator_id bigint REFERENCES public.indicators(id),
  description text,
  frameworks jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.data_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  unit character varying,
  data_type character varying,
  definition text,
  embedding vector(1536),
  created_at timestamp with time zone DEFAULT now(),
  data_id bigint REFERENCES public.data(id)
);

CREATE TABLE IF NOT EXISTS public.data_point_synonyms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_point_id bigint REFERENCES public.data_points(id),
  term text NOT NULL UNIQUE,
  embedding vector(1536),
  created_at timestamp with time zone DEFAULT now()
);

-- ── 4. standardized_data (raw_data, data_points 참조) ─────────

CREATE TABLE IF NOT EXISTS public.standardized_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type character varying,
  site_id character varying,
  reporting_date date,
  metric_name text REFERENCES public.data_points(name),
  data_point_id bigint REFERENCES public.data_points(id),
  value double precision,
  unit character varying,
  raw_value_text text,
  original_value double precision,
  v_status smallint DEFAULT 0 CHECK (v_status >= 0 AND (v_status <= 5 OR v_status = 99)),
  standardization_confidence double precision CHECK (
    standardization_confidence IS NULL OR
    (standardization_confidence >= 0 AND standardization_confidence <= 1)
  ),
  updated_by text,
  correction_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  raw_data_id bigint REFERENCES public.raw_data(id),
  CONSTRAINT standardized_data_unique UNIQUE (source_type, site_id, reporting_date, metric_name)
);

-- ── 5. master_sites 참조 테이블들 ─────────────────────────────

CREATE TABLE IF NOT EXISTS public.activity_data (
  activity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id text REFERENCES public.master_sites(site_id),
  reporting_date date NOT NULL,
  production_qty double precision,
  unit text DEFAULT 'Ton'::text
);

CREATE TABLE IF NOT EXISTS public.evidence_usage (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id text REFERENCES public.master_sites(site_id),
  reporting_date date NOT NULL,
  metric_name text NOT NULL,
  unit text NOT NULL,
  ocr_value double precision,
  file_name text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.site_metric_map (
  customer_number text NOT NULL PRIMARY KEY,
  site_id text REFERENCES public.master_sites(site_id),
  metric_name text NOT NULL,
  unit text NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS public.threshold_limits (
  site_id text NOT NULL REFERENCES public.master_sites(site_id),
  metric_name text NOT NULL,
  unit text NOT NULL,
  upper_limit double precision,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (site_id, metric_name)
);

-- ── 6. standardized_data 참조 테이블들 ────────────────────────

CREATE TABLE IF NOT EXISTS public.outlier_results (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  std_id bigint REFERENCES public.standardized_data(id) ON DELETE CASCADE,
  layer text,
  detected_value double precision,
  threshold double precision,
  severity text,
  analysis_summary text,
  z_score double precision,
  yoy_roc double precision,
  intensity_deviation double precision,
  is_resolved boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.audit_trail (
  trail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  std_id bigint NOT NULL REFERENCES public.standardized_data(id) ON DELETE CASCADE,
  action text NOT NULL,
  before_value double precision,
  after_value double precision,
  before_status integer,
  after_status integer,
  reason text,
  performed_by text NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.justification_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  std_id bigint NOT NULL REFERENCES public.standardized_data(id) ON DELETE CASCADE,
  outlier_id integer REFERENCES public.outlier_results(id) ON DELETE SET NULL,
  justification_type text NOT NULL DEFAULT 'user_input',
  user_feedback text NOT NULL,
  action_taken text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.verification_logs (
  log_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  std_id bigint REFERENCES public.standardized_data(id) ON DELETE CASCADE,
  evidence_id integer REFERENCES public.evidence_usage(id),
  gap_value double precision,
  gap_percent double precision,
  result_code integer,
  diagnosis text,
  verified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  db_value double precision,
  ocr_value double precision,
  unit_mismatch boolean DEFAULT false,
  verified_by text,
  approved_at timestamp with time zone
);

-- ── 7. 벡터 검색 인덱스 (선택 사항 — 데이터 적재 후 생성 권장) ──
-- CREATE INDEX ON public.data_points USING ivfflat (embedding vector_cosine_ops);
-- CREATE INDEX ON public.data_point_synonyms USING ivfflat (embedding vector_cosine_ops);
